name: Windows Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string
        default: '0.1.0-1'
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'Version number'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'
          channel: 'stable'
          cache: true # Add caching for better performance
        env:
          LANG: en_US.UTF-8

      # Cache pub dependencies separately
      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.PUB_CACHE }}
            .dart_tool/
          key: pub-dependencies-windows-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            pub-dependencies-windows-${{ runner.os }}-

      - name: Install CMake
        uses: lukka/get-cmake@latest
        
      - name: Install Windows SDK
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Download Icon
        run: |
          # Create assets directory if it doesn't exist
          if (!(Test-Path "assets")) {
              New-Item -ItemType Directory -Path "assets" -Force
          }
          
          # Download icon directly from GitHub without needing conversion
          $iconUrl = "https://raw.githubusercontent.com/ALi3naTEd0/ocrme/main/assets/logo.ico"
          $iconUrlFallback = "https://raw.githubusercontent.com/ALi3naTEd0/ocrme/main/assets/logo.png"
          $outputPath = "assets/logo.ico"
          
          try {
              Invoke-WebRequest -Uri $iconUrl -OutFile $outputPath -ErrorAction Stop
              Write-Host "Icon downloaded successfully from: $iconUrl"
          } catch {
              Write-Host "Failed to download ICO, trying PNG fallback..."
              try {
                  Invoke-WebRequest -Uri $iconUrlFallback -OutFile "assets/logo.png" -ErrorAction Stop
                  Write-Host "PNG fallback downloaded successfully"
                  Copy-Item "assets/logo.png" -Destination $outputPath -Force
              } catch {
                  Write-Host "Failed to download icon. Creating placeholder..."
                  # Create a simple placeholder
                  $tempFile = New-TemporaryFile
                  Add-Type -AssemblyName System.Drawing
                  $bitmap = New-Object System.Drawing.Bitmap 256, 256
                  $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
                  $graphics.Clear([System.Drawing.Color]::Purple)
                  $bitmap.Save($tempFile.FullName, [System.Drawing.Imaging.ImageFormat]::Png)
                  $bitmap.Dispose()
                  $graphics.Dispose()
                  Copy-Item $tempFile.FullName -Destination $outputPath -Force
                  Remove-Item $tempFile.FullName -Force
              }
          }
          
          if (Test-Path $outputPath) {
              Write-Host "Icon is ready at: $outputPath"
          } else {
              Write-Error "Failed to prepare icon"
              exit 1
          }

      # Cache tessdata files
      - name: Download Tessdata
        shell: pwsh
        id: cache-tessdata
        run: |
          # Check if tessdata has already been cached
          $tessdataPath = "assets/tessdata"
          $enginePath = "assets/eng.traineddata"
          $spanishPath = "assets/spa.traineddata"
          
          if (!(Test-Path $tessdataPath)) {
              Write-Host "Creating tessdata directory"
              New-Item -ItemType Directory -Path $tessdataPath -Force
              
              Write-Host "Downloading tessdata files"
              # Download English and Spanish language files
              Invoke-WebRequest -Uri "https://github.com/tesseract-ocr/tessdata_fast/raw/main/eng.traineddata" -OutFile "$tessdataPath/eng.traineddata"
              Invoke-WebRequest -Uri "https://github.com/tesseract-ocr/tessdata_fast/raw/main/spa.traineddata" -OutFile "$tessdataPath/spa.traineddata"
              
              Write-Host "Tessdata files downloaded successfully"
          } else {
              Write-Host "Tessdata directory already exists, checking files"
              
              if (!(Test-Path "$tessdataPath/eng.traineddata")) {
                  Write-Host "Downloading English tessdata"
                  Invoke-WebRequest -Uri "https://github.com/tesseract-ocr/tessdata_fast/raw/main/eng.traineddata" -OutFile "$tessdataPath/eng.traineddata"
              }
              
              if (!(Test-Path "$tessdataPath/spa.traineddata")) {
                  Write-Host "Downloading Spanish tessdata"
                  Invoke-WebRequest -Uri "https://github.com/tesseract-ocr/tessdata_fast/raw/main/spa.traineddata" -OutFile "$tessdataPath/spa.traineddata"
              }
              
              Write-Host "Tessdata files verified"
          }

      # Install dependencies first to improve build performance
      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Setup Windows build
        run: flutter config --enable-windows-desktop

      # Add this step to prepare for the build and avoid the CMake error
      - name: Prepare Build Environment
        shell: pwsh
        run: |
          # Create native_assets directory to prevent the CMake error
          New-Item -ItemType Directory -Path "build\native_assets\windows" -Force -ErrorAction SilentlyContinue
          
          # Create directories that might be referenced by CMake
          New-Item -ItemType Directory -Path "build\windows\x64\runner\Release" -Force -ErrorAction SilentlyContinue
          
          # Check CMake version
          & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe' --version
          
          # Make sure the install path exists and is writable
          $installDir = Join-Path $env:GITHUB_WORKSPACE "build\windows\install"
          New-Item -ItemType Directory -Path $installDir -Force -ErrorAction SilentlyContinue
          
          # Set explicit permissions (this shouldn't be necessary in most cases but might help)
          $acl = Get-Acl $installDir
          $rule = New-Object System.Security.AccessControl.FileSystemAccessRule("BUILTIN\Users", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")
          $acl.SetAccessRule($rule)
          Set-Acl $installDir $acl
          
          Write-Host "Build environment prepared"

      - name: Build Windows
        run: |
          # Add verbose output to see what's happening
          flutter -v build windows --release --no-pub

      - name: Create Portable ZIP
        shell: pwsh
        run: |
          $version = "${{ inputs.version || github.event.inputs.version }}"
          
          $portableDirName = "OCRMe_${version}_portable"
          
          # Create portable directory and copy files
          New-Item -ItemType Directory -Path $portableDirName -Force
          Copy-Item -Path "build\windows\x64\runner\Release\*" -Destination $portableDirName -Recurse -Force
          
          # Create data directory with tessdata
          New-Item -ItemType Directory -Path "$portableDirName\data\tessdata" -Force
          Copy-Item -Path "assets\tessdata\*" -Destination "$portableDirName\data\tessdata" -Force
          
          # Create empty settings file if it doesn't exist
          if (!(Test-Path "$portableDirName\data\settings.json")) {
              Set-Content -Path "$portableDirName\data\settings.json" -Value "{}"
          }
          
          # Create ZIP archive
          $zipFileName = "OCRMe_${version}_portable.zip"
          Compress-Archive -Path "$portableDirName\*" -DestinationPath $zipFileName -Force

      - name: Upload Portable ZIP
        uses: actions/upload-artifact@v4
        with:
          name: OCRMe-portable
          path: OCRMe_${{ inputs.version || github.event.inputs.version }}_portable.zip

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Create Installer
        shell: pwsh
        env:
          VERSION: ${{ inputs.version || github.event.inputs.version }}
        run: |
          New-Item -ItemType Directory -Path "installers\Output" -Force
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' installers\inno_setup_script.iss

      - name: Upload Setup Package
        uses: actions/upload-artifact@v4
        with:
          name: OCRMe-Setup
          path: installers/Output/OCRMe_${{ inputs.version || github.event.inputs.version }}.exe